---
name: Sedge test suite
on:
  push:
    branches:
      - main
jobs:
  sedge-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"
      - name: Download and build Sedge
        run: >
          echo "Downloading sedge sources..."

          git clone https://github.com/NethermindEth/sedge.git src --branch main --single-branch

          echo "Sources downloaded."

          cd src

          echo "Building sedge..."

          make compile
      - name: Run Sedge tool
        run: >
          echo 'Running sedge...'

          ./sedge deps install >> $HOME/sedge.logs

          ./sedge generate --logging none -p $HOME /full-node --map-all --no-mev-boost --no-validator --network chiado /-c lighthouse:sigp/lighthouse:latest -e nethermind:nethermindeth/nethermind:master /--el-extra-flag Sync.NonValidatorNode=true --el-extra-flag Sync.DownloadBodiesInFastSync=false /--el-extra-flag Sync.DownloadReceiptsInFastSync=false /--cl-extra-flag checkpoint-sync-url=http://139.144.26.89:4000/ >> $HOME/sedge.logs

          ./sedge run -p . >> $HOME/sedge.logs
