name: Sedge test suite

on:
  push:
    branches:
      - main

jobs:
  sedge-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Download and build Sedge
        run: |
          echo "Downloading sedge sources..."
          git clone https://github.com/NethermindEth/sedge.git src --branch main --single-branch
          echo "Sources downloaded."
          cd src
          echo "Building sedge..."
          make compile
          cd build
          ls -lrt
